# Numpy Matrix

* Before starting out, first import numpy (preferably as np for ease of use later)

In [1]:
import numpy as  np

* In order to understand how numpy arrays work, you first have to understand how matrix works in math. Let's start with a <b> 2*2 matrix</b>

* As its name suggests, it needs to have 2 rows and 2 columns:

* For example, let's go ahead and create a numpy array using np.array()

In [2]:
two_by_two=np.array([["a","b"],
                    ["c","d"]])

In [3]:
two_by_two

array([['a', 'b'],
       ['c', 'd']], dtype='<U1')

* To find the determinant of a 2\*2 array, you have to do this d= (a\*d)-(b\*c)

* Let's see how a 3\*3 array works:

 |a b c|  
 |d e f|  
 |g h i| 

* You can find the determinant of a 3*3 array with 2 methods.
* Let's see the first one:

* We start from the top left and go diagonally down, then the the second on the top, and the third. When starting from the top, we use + in front.
* We have to start from the top with the + sign and then from the bottom with the 0 sign in front (make sure to put the + and - symbols right.)
    * As you can see, i wrote the first two lines after the || finishen for ease. 
    * Please keep in mind that **+\*+ = +** , **- \*-=-** , **+ \* - = -**
* The symbols in the ( ) remain and at the end you change them accordingly

* **The second way, you can use for any squared matrix:**

* You can choose whichever line you like, just remember the symbols should be **+ - +**
* in order to find the determinant using this way, you stsart from the first letter/number of the line and you 'cancel out' the line and row that it is in.
* Then, you take the numbers/letters that are left (that you didn't cancel out) and create a smaller, 2\*2 matrix and solve it as we learnet at first.
* If the matrix is 4\*4, 5\*5, you just pick a line, and start simplifying until you get a 2*2 matrix. The symbols (not of the numbers, but of weather you are going to + or - between each one) are  + - + - + - .........

I hope it was clear. Don't worry if you didn't fully understand it. You can watch these videos to understand it better:  
[Method 1](https://www.khanacademy.org/math/algebra-home/alg-matrices/alg-determinants-and-inverses-of-large-matrices/v/finding-the-determinant-of-a-3x3-matrix-method-2)  
[Method 2](https://www.khanacademy.org/math/algebra-home/alg-matrices/alg-determinants-and-inverses-of-large-matrices/v/finding-the-determinant-of-a-3x3-matrix-method-1) 

* Let's start by talking about data types in numpy

* please note that integer:number with no decimal point
    * float:number witih decimal points
    * string: with characters
    * python object: dictionaries [Click Here to learn more](https://www.w3schools.com/python/python_dictionaries.asp) about dictionaries
  
<p>don't worry if you don't understand how the array creation works, it will be explained later. Just make sure to understand the different types of data and how to get the type of an array.</p>

* Things to know for numpy data types:
    * The actual data type
    * Size of tha data (eg. of the integer - 32-bit, 64-bit etc.)
    * Byte order - little-endian, big-endian \*
    * If the data is a nested array and its data type
    
    
        * Little-endian: The piece of data with the smallest value is placed at the byte with the lowest address. The rest of the data is placed in order in the next 3 bytes
        * big-endian: The piece of data with the biggest value is placed at the byte with the lowest address. The rest the the data is placed in order in the next 3 bytes
        
We use .dtype to get the type

In [4]:
arr2=np.array({1:"o means python object"})
arr2.dtype

dtype('O')

In [5]:
arr2=np.array([[1,2,3,4],
              [1,2,3,4]])
arr2.dtype

dtype('int64')

* In order create a numpy array, create a variable and use np.array() and for each row create an array separating it with comas (,)

In [6]:
arr1=np.array([[3,4,6,8],
              [10,24,54,55],
              [21,23,46,13],
              [31,23,54,21]])

* This is how you get the determinant of a squared array (matrix).

In [7]:
np.linalg.det(arr1)

39691.99999999997

* You can find the  sine (sin),cosine (cos), and tangent(tan) of all the values:

In [8]:
np.sin(arr1)

array([[ 0.14112001, -0.7568025 , -0.2794155 ,  0.98935825],
       [-0.54402111, -0.90557836, -0.55878905, -0.99975517],
       [ 0.83665564, -0.8462204 ,  0.90178835,  0.42016704],
       [-0.40403765, -0.8462204 , -0.55878905,  0.83665564]])

In [9]:
np.cos(arr1)

array([[-0.9899925 , -0.65364362,  0.96017029, -0.14550003],
       [-0.83907153,  0.42417901, -0.82930983,  0.02212676],
       [-0.54772926, -0.53283302, -0.43217794,  0.90744678],
       [ 0.91474236, -0.53283302, -0.82930983, -0.54772926]])

In [10]:
np.tan(arr1)

array([[ -0.14254654,   1.15782128,  -0.29100619,  -6.79971146],
       [  0.64836083,  -2.1348967 ,   0.6738001 , -45.18308791],
       [ -1.52749853,   1.58815308,  -2.08661353,   0.46302113],
       [ -0.44169557,   1.58815308,   0.6738001 ,  -1.52749853]])

* create an array with zeros or ones - .zeros or .ones and double () and then the number of the columns and rows. If we want a 1-column array, we just add (columns)

In [11]:
zeros=np.zeros((5,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
ones=np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
zeros1=np.zeros(5)
zeros1

array([0., 0., 0., 0., 0.])

* if you would like to create a 1-row array and reshappe it latter, you can use .reshape()

In [14]:
resh=np.array([1.3425234,2.342,3.24324323653226,4.23535,5.234523,6.34523,7.353,8.354325335
               ,9.32,10.345,11.1245345142,12.455547,13.35345,14.3453,15.3534433534])
resh=resh.reshape(5,3)

In [15]:
resh

array([[ 1.3425234 ,  2.342     ,  3.24324324],
       [ 4.23535   ,  5.234523  ,  6.34523   ],
       [ 7.353     ,  8.35432534,  9.32      ],
       [10.345     , 11.12453451, 12.455547  ],
       [13.35345   , 14.3453    , 15.35344335]])

In [16]:
resh=resh.reshape(3,5)
resh

array([[ 1.3425234 ,  2.342     ,  3.24324324,  4.23535   ,  5.234523  ],
       [ 6.34523   ,  7.353     ,  8.35432534,  9.32      , 10.345     ],
       [11.12453451, 12.455547  , 13.35345   , 14.3453    , 15.35344335]])

* .reshape(rows,columns)
* in order for it to run wihout errors you have to write integers in the () and when you multiply the 2 numbers that you wrote, the result has to be equal to the number of items in the main array

* You can use .around() to change the decimal points in an array:
* out=... is optional
* np.around(array,decimals,out)

In [17]:
np2=np.around(resh,4,out= None)
np2

array([[ 1.3425,  2.342 ,  3.2432,  4.2354,  5.2345],
       [ 6.3452,  7.353 ,  8.3543,  9.32  , 10.345 ],
       [11.1245, 12.4555, 13.3534, 14.3453, 15.3534]])