# Numpy Operations & Functions

In [120]:
import numpy as np

* By now, you should be familiar with creating a numpy array. Let me show you some useful operations

In [121]:
arr1=np.array([10,20,30,40,50])
arr2=np.array([5,10,15,20,60])
print("1st Array",arr1)
print("2st Array",arr2)

1st Array [10 20 30 40 50]
2st Array [ 5 10 15 20 60]


* You can perform arithmetic operations with 2 arrays

In [122]:
arr3=arr1+arr2
arr4=arr1/arr2
print("1st and 2nd array invited",arr3)
print("1st and 2nd array divided",arr4)

1st and 2nd array invited [ 15  30  45  60 110]
1st and 2nd array divided [2.         2.         2.         2.         0.83333333]


* If you add arrays with the same dimension but a different number of elements, you will get an error
* Using the same method, you can perform operations on multi-dimentional arrays

* You can also use operations with one number in an array:

In [123]:
arr3=arr1*5
arr3

array([ 50, 100, 150, 200, 250])

* Or use ** to find the square of the numbers
* If you would like to use a higher power, use the pow() cuntion

In [124]:
arr3=pow(arr1,5)
arr3

array([   100000,   3200000,  24300000, 102400000, 312500000])

* Conditional Expressions:
* Fills the array with True and False statements according to the expression

In [125]:
arr4=arr1>=arr2
arr4

array([ True,  True,  True,  True, False])

* import random library and use it to generate a random number:

In [126]:
import random
a1=np.array([random.randint(2,7)])
a1

array([4])

* Use .min to find the lowest value in the array.

In [127]:
arr1.min()

10

* Use .sum() to sum the values of an axis or the whole matrix:

In [128]:
arr4.sum()
arr4.sum(axis=0)

4

* Use .max() to find the biggest number:

In [129]:
arr3.max()

312500000

### Axis

* Let's give an example to help you understand axis:
    * In a 2-dimentional array, you have 2 axes.
    * Axis 0 is vertical down the rows
    * Axis 1 is horizontal from left to right across the columns

* When using functions like .mean(), you can specify the axis to run on:

In [130]:
axes=np.array([[1,2,3,4,5],
              [6,7,8,9,0]])
np.mean(axes,axis=1)

array([3., 6.])

In [131]:
np.mean(axes,axis=0)

array([3.5, 4.5, 5.5, 6.5, 2.5])

## Matrix Multiplication

* Matrix Multiplication, is a binnary operation that gives out a matrix from 2 matrices

Things that you should know:
* Rows: Horisontal (->) 
* Columns: Vertical (|)
* <b>VERY IMPORTANT: The no. of colummns in the 1st matrix should be equal to the no. of rows of the 2nd one.</b>
    * If this isn't true for the matrices that you are using, try doina B\*A, as it actually matters for them to be equal.
* The columns and rows of a matrix can be represented like this: [rows\*columns]
* The matrix that comes out, is named <b>matrix product</b>
* The <u>matrix product</u> has the number of <i>rows</i> of the <i>first</i> and the  no of the <i>columns</i> of the <i>second</i> one.
* Let's call the 1st one <b>A</b> and the second one <b>B</b> - the matrix product is <b>AB</b>

<u>A: 1 row, 3 columns  
B: 3 rows, 2 columns</u>
AB: 1(A-rows) \* 2 (B-columns) -> 1 row, 2 columns

* For the multiplication, we multiply the numbers of the 1st matrix with each nummber from the second one. Don't be scared by the formula, just try to understand it.

* Since we are multiplying the 1st columns with the 1 st row, the number that will be coming out will be put to column 1 and row 1 of AB

What about multiplying multi-dimentional matrices? <b>Let's have a look at an example</b>

A*B= [3\*2]\*[2\*3] -> The columns of A are the same no. with the rows of B, so they can be multiplied.

AB is going to be [Arows\*Bcolumns], so [3\*3]

* Back to numpy, you can get the miltiplication of twomatrices by using the dot function - the same rules apply:

In [132]:
A=np.array([[1,2,3,4,5],
           [1,2,3,4,5]])
B=np.array([[1,2,3],
            [6,5,4],
            [4,2,6],
            [9,6,7],
            [4,9,1]])

In [133]:
AB=A.dot(B)
AB

array([[81, 87, 62],
       [81, 87, 62]])

* You can also use the @ symbol: 

In [134]:
AB2=A@B
AB2

array([[81, 87, 62],
       [81, 87, 62]])

## Other functions

* There are arithmetic operations avalable in functions, like <b>/add</b>, <b>.subtract</b> <b>.multiply</b> and <b>.divide</b>

In [135]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
a=a.reshape(5,2)
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [136]:
a1=np.array([4,6])

* Adding a 1-dimentional array to a 2-dimentional one. - .add(arr1,arr2)

In [137]:
a2=np.add(a,a1)

In [138]:
a2

array([[ 5,  8],
       [ 7, 10],
       [ 9, 12],
       [11, 14],
       [13, 16]])

* <b>_like,</b>

We learnet that we can create an array filled with zeros or ones. Using <b>_like</b>, we can create that array, in theshape ofan existing array:

In [139]:
a1=np.ones_like(a2)
a1

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

*or <b>full_like(arr,number)</b> to fill it in that shape with the number that you type

In [140]:
a1=np.full_like(a2,6)
a1

array([[6, 6],
       [6, 6],
       [6, 6],
       [6, 6],
       [6, 6]])

* You can also use empty_like and zeros_like

[Click Here](https://stackoverflow.com/questions/14415741/what-is-the-difference-between-numpys-array-and-asarray-functions) to learn about asarray() - there are some differences with array()

* Use <b>.arange()</b> to generate numbers - .arange(start,stop,step)
   * step = th gap between the numbers
   * start - the number that you give is included
   * stop: the number that you give is not included

In [141]:
a1=np.arange(10,50,1)
a1
# and reshape it
a1.reshape(4,10)

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

* Use <b>np.linspace(start,stop,quantity_of_numbers)</b> to genetate numbers with random spaces between then - eg. you cen generate 6 numbers from numbers 1-3
    * If you add <b>retstep=true</b>, the spacing between the numbers will be even.

In [154]:
a1=np.linspace(3,4,4)
a1

array([3.        , 3.33333333, 3.66666667, 4.        ])

In [150]:
a2=np.linspace(3,4,4, retstep=True)
a2

(array([3.        , 3.33333333, 3.66666667, 4.        ]), 0.3333333333333333)

* Get the shape of an array using .shape

In [152]:
arr1.shape

(5,)

* Make the array one-dimention

In [157]:
arr2=np.array([[1,2,3],
              [1,2,3]])
arr2=arr2.flatten()
arr2

array([1, 2, 3, 1, 2, 3])

* Useful in ML, we can split each row into its own column - .vsplit(array,number_of_rows)

In [159]:
arr2=np.array([[1,2,3],
              [1,2,3]])
arr2=np.vsplit(arr2,2)
arr2

[array([[1, 2, 3]]), array([[1, 2, 3]])]

* Again useful in ML, splitting columns into separate arrays. - .hsplit(array,number_of_columns)

In [161]:
arr2=np.array([[1,2,3],
              [1,2,3]])
arr2=np.hsplit(arr2,3)
arr2

[array([[1],
        [1]]),
 array([[2],
        [2]]),
 array([[3],
        [3]])]